###################################################################   ####  # ##
# >>  DOCKERFILE-WEBGUI-V2
###################################################################   ####  # ##

# install nignx and php

ARG WEBGUI_CERT
ARG WEBGUI_PASSWORD
FROM alpine:3.16
LABEL org.opencontainers.image.source=https://github.com/silv3rr/docker-glftpd
EXPOSE 443
WORKDIR /app
COPY --chown=0:0 etc/nginx /etc/nginx
COPY --chown=100:101 var/www/webgui /app
ADD --chown=100:101 var/www/fontawesome-free-6.1.2-web.tar.gz /app/lib
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
# hadolint ignore=SC2016,SC2086,DL3018
RUN test -n "$http_proxy" && { \
      http_proxy=${http_proxy}; \
      https_proxy=${http_proxy}; \
      sed -i 's/https/http/g' /etc/apk/repositories ;\
    }; \
    apk add --no-cache \
      nginx \
      php8 \
      php8-fpm \
      php8-session \
      php8-ftp \
      php8-curl \
      php8-json \
      php8-ctype \
      apache2-utils \
      openssl && \
    rm -rf /var/cache/apk/* && \
    install -d -m 0755 -o nginx -g nginx /run/nginx && \
    install -d -m 0755 -o nginx -g nginx /run/php && \
    rm /etc/nginx/http.d/default.conf && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log && \
    sed -i 's|listen = 127.0.0.1:9000|listen = /run/php/php8-fpm.sock|' /etc/php8/php-fpm.d/www.conf && \
    sed -i 's|;listen.owner = nobody|listen.owner = nginx|' /etc/php8/php-fpm.d/www.conf && \
    sed -i 's|;listen.group = nobody|listen.owner = nginx|' /etc/php8/php-fpm.d/www.conf && \
    # generate self-signed cert
    if [ "${WEBGUI_CERT:-1}" -eq 1 ]; then \
      if [ ! -e /etc/nginx/webgui.crt ] && [ ! -e /etc/nginx/webgui.key ]; then \
        openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
          -config /etc/nginx/webgui.cnf \
          -keyout /etc/nginx/webgui.key \
          -out /etc/nginx/webgui.crt && \
        chmod 600 /etc/nginx/webgui.key; \
      fi; \
    fi && \
    # set password
    HTPASSWD='shit:$apr1$8kedvKJ7$PuY2hy.QQh6iLP3Ckwm740'; \
    if [ -n "$WEBGUI_PASSWORD" ]; then \
      HTPASSWD="$( echo $WEBGUI_PASSWORD | htpasswd -n -i shit )"; \
    fi; \
    echo "$HTPASSWD" > /etc/nginx/.htpasswd && \
    addgroup nobody ping || true && \
    { echo '#!/bin/sh'; \
      echo 'DOCKER_GID="$( stat -c %g /var/run/docker.sock )"'; \
      echo 'grep -Eq "^docker:" /etc/group || echo "docker:x:${DOCKER_GID:-999}:nobody" >>/etc/group'; \
      echo 'php-fpm8 -F &'; \
      echo 'nginx -g "daemon off;"'; \
    } >/docker-cmd.sh
CMD ["sh", "/docker-cmd.sh"]
