---
###################################################################   ####  # ##
# >> DOCKER-COMPOSE-GLFTPD
###################################################################   ####  # ##
# build args:           see docker-build.sh comments
# environment options:  see docker-run.sh comments
###################################################################   ####  # ##

version: "3"
services:
  glftpd:
    build:
      context: .
      cache_from:
        - glftpd:latest
      dockerfile: Dockerfile
      args:
        - GLFTPD_URL="https://silv3rr.bitbucket.io/files/glftpd-LNX-2.13_3.0.7_x64.tgz"
        - GLFTPD_HASH="fdf52bec305140b14e7707d922793b828084c0ab237ff0d0f9d3a70af63c5b3e7c0d4a6d6f862021ed5c17f396812790539915ee8889709a60af95eafcc6dfd5"
        - INSTALL_ZS=1 
        - INSTALL_BOT=1
        # - ARGS=
    image: glftpd:latest
    volumes:
      - ./glftpd/site:/glftpd/site:rw
      - ./glftpd/glftpd.conf:/glftpd/glftpd.conf
      - ./glftpd/etc:/glftpd/etc
      - ./glftpd/ftp-data/users:/glftpd/ftp-data/users
      - ./glftpd/sitebot/eggdrop.conf:/glftpd/sitebot/eggdrop.conf
      - ./glftpd/sitebot/LamestBot.chan:/glftpd/sitebot/LamestBot.chan
      - ./glftpd/sitebot/LamestBot.user:/glftpd/sitebot/LamestBot.user
      - ./pzs-ng/sitebot/ngBot.conf:/glftpd/sitebot/pzs-ng/ngBot.conf
    ports:
      - "1337:1337"
      # uncomment for bot
      # - "3333:3333"
      # - "5000-6000:5000-6000"
    container_name: glftpd
    hostname: glftpd
    environment:
      - GLFTPD_CONF=0
      # uncomment to change password
      # - GLFTPD_PASSWD=glftpd
      - GLFTPD_PERM_UDB=0
      - GLFTPD_SITE=0
      - GLFTPD_PORT=1337
      - GLFTPD_PASV_PORTS=5000-6000
      - INSTALL_BOT=1
      # - ARGS=
  web:
    build:
      context: web
      cache_from:
        - glftpd-web:latest
      dockerfile: Dockerfile
      args:
        - WEB_PASSWORD=Anothersh1ttyPass
    image: glftpd-web:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
      - ./glftpd/glftpd.conf:/glftpd/glftpd.conf
      - ./glftpd/sitebot/eggdrop.conf:/glftpd/eggdrop.conf
      - ./pzs-ng/sitebot/pzs-ng/ngBot.conf:/glftpd/ngBot.conf
      - ./glftpd/site:/site/glftpd
    ports:
      - 4444:443
    container_name: web
    hostname: web
    #environment:

# volumes:
