name: Docker build and push

on:
  push:
    branches: [master, main]
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '!README.md'
  pull_request:
  workflow_dispatch:

jobs:
  docker-images:
    name: Build Docker images and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build images
        run: INSTALL_WEB=1 INSTALL_ZS=0 INSTALL_BOT=0 ./docker-build.sh
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          docker tag docker-glftpd:latest ghcr.io/silv3rr/docker-glftpd:latest
          docker tag docker-glftpd-web:latest ghcr.io/silv3rr/docker-glftpd-web:latest
          docker push ghcr.io/silv3rr/docker-glftpd:latest
          docker push ghcr.io/silv3rr/docker-glftpd-web:latest
      - name: Build full image
        run: INSTALL_WEB=0 INSTALL_ZS=1 INSTALL_BOT=1 ./docker-build.sh
      - name: Push full image
        run: |
          docker tag glftpd:latest ghcr.io/silv3rr/docker-glftpd:full
          docker push ghcr.io/silv3rr/docker-glftpd:full
