name: Docker build and push

on:
  push:
    branches: [master, main]
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '!README.md'
  pull_request:
  workflow_dispatch:

# glftpd.io is down
env:
  GLFTPD_URL: "https://mirror.glftpd.nl.eu.org/files/glftpd-LNX-2.14a_3.0.12_x64.tgz"

jobs:
  docker-images:
    name: Build Docker images and push to repositories
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build basic glftpd image
        run: INSTALL_WEBUI=0 INSTALL_ZS=0 INSTALL_BOT=0 ./docker-build.sh
      - name: Push images
        run: |
          docker tag docker-glftpd:latest ghcr.io/silv3rr/docker-glftpd:latest
          docker push ghcr.io/silv3rr/docker-glftpd:latest
      - name: Build full glftpd image
        run: INSTALL_WEBUI=1 INSTALL_ZS=1 INSTALL_BOT=1 ./docker-build.sh
      - name: Push full image
        run: |
          docker tag docker-glftpd:latest ghcr.io/silv3rr/docker-glftpd:full
          docker push ghcr.io/silv3rr/docker-glftpd:full
